<%@page language="java" contentType="text/html; charset=ISO-8859-1"	pageEncoding="ISO-8859-1"%>
<%@taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@taglib prefix="jstl" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<p><strong>INFORMACION LEGAL</strong></p>
<p>El acceso a la p&aacute;gina web www.acme-bnb.com y sus contenidos es libre y voluntario. Los usuarios quedan sujetos a las siguientes condiciones relativas a los servicios y contenidos de la p&aacute;gina</p>
<ol>
    <li>ACME INC. elabora esta web con informaci&oacute;n procedente de fuentes internas y externas, por lo que no se garantiza la exhaustividad y exactitud de la informaci&oacute;n.</li>
    <li>ACME INC. asegura la confidencialidad de los datos aportados por los usuarios a trav&eacute;s de correo electr&oacute;nico a la direcci&oacute;n de contacto establecida en la web, y garantiza que en ning&uacute;n caso ser&aacute;n cedidos a terceros. En cumplimiento de lo dispuesto en la Ley Org&aacute;nica 15/1999 de 13 de Diciembre de Protecci&oacute;n de Datos de Car&aacute;cter Personal, ACME INC. le informa que podr&aacute; ejercitar los derechos de acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n remitiendo un escrito identificado con la referencia "Protecci&oacute;n de Datos", en el que se concrete su solicitud y al que acompa&ntilde;e fotocopia de su Documento Nacional de Identidad, dirigido a info@acme-bnb.com El afectado tambi&eacute;n puede ejercitar sus derechos mediante la remisi&oacute;n de un correo electr&oacute;nico anexando el DNI escaseado a <a href="mailto:info@acme-bnb.com">info@acme-bnb.com</a></li>
    <li>ACME INC. no se responsabiliza del mal uso que se realice de los contenidos de su p&aacute;gina web, siendo exclusiva responsabilidad de la persona que accede a ellos o los utilice. ACME INC. no asume responsabilidad alguna por la informaci&oacute;n contenida en p&aacute;ginas electr&oacute;nicas de terceros a las que se pueda acceder por enlaces (links) o buscadores.</li>
    <li>La presencia de enlaces en la p&aacute;gina web de ACME INC. tiene finalidad meramente informativa, y en ning&uacute;n caso supone sugerencia, invitaci&oacute;n o recomendaci&oacute;n sobre ellos. ACME INC. declina toda responsabilidad que se derive del intercambio de informaci&oacute;n entre usuarios a trav&eacute;s de sus p&aacute;ginas electr&oacute;nicas. La responsabilidad de las manifestaciones difundidas en dichas p&aacute;ginas corresponde a quienes las realizan.</li>
    <li>ACME INC. no ser&aacute; responsable de los posibles da&ntilde;os o perjuicios que se pudieran derivar de interferencias, omisiones, interrupciones, virus inform&aacute;ticos, aver&iacute;as telef&oacute;nicas o desconexiones en el funcionamiento operativo de este sistema electr&oacute;nico; de los retrasos o bloqueos en el uso del presente sistema electr&oacute;nico causados por deficiencias o sobrecargas de las l&iacute;neas telef&oacute;nicas o por sobrecargas en el sistema de Internet o en otros sistemas electr&oacute;nicos; as&iacute; como de los da&ntilde;os que puedan ser causados por terceras personas mediante intromisiones ileg&iacute;timas fuera del control de la empresa. Asimismo, se exonera a ACME INC. de responsabilidad ante cualquier da&ntilde;o o perjuicio que pudiera sufrir el usuario como consecuencia de errores, defectos u omisiones en la informaci&oacute;n facilitada ACME INC. siempre que proceda de fuentes ajenas a la empresa.</li>
    <li>ACME INC. podr&aacute; modificar unilateralmente y sin previo aviso, siempre que lo considere oportuno, la estructura y el dise&ntilde;o de su web, as&iacute; como modificar o eliminar los servicios, los contenidos y las condiciones de acceso y uso.</li>
    <li>Los derechos de propiedad intelectual del contenido de la p&aacute;gina web, de su dise&ntilde;o gr&aacute;fico y sus c&oacute;digos fuente son titularidad de ACME INC., por tanto, quedan prohibidas su reproducci&oacute;n, distribuci&oacute;n, comunicaci&oacute;n p&uacute;blica y transformaci&oacute;n. Igualmente est&aacute;n protegidos por la ley todos los nombres comerciales, marcas o signos de cualquier clase contenidos en la p&aacute;gina web de ACME INC.</li>
</ol>
<p>&nbsp;</p>
<ol start="8">
    <li>Respecto a las citas de productos y servicios de terceros, ACME INC. reconoce a favor de sus titulares los correspondientes derechos de propiedad intelectual e industrial; su sola menci&oacute;n o aparici&oacute;n en la p&aacute;gina web no implican la existencia de derechos o responsabilidad alguna de ACME INC. sobre ellos.</li>
</ol>